### ISSUE TITLE
`logout` event not fired when user logout the bot on their phone

### ISSUE THREAD

**Issue by huan** [wechaty/wechaty-puppet-padplus#100]
> Important：Please file the issue follow the template, or we won't help you to solve the problem.

## 1. Versions

- What is your wechaty-puppet-padplus version?
Answer:0.1.3

## 2. Describe the bug

Give a clear and concise description of what the bug is.

The `logout` event not fired. It should be fired when user log bot out on their phone wechat app.

## 3. To Reproduce

This part is very important: if you can not provide any reproduce steps, then the problem will be very hard to be recognized.

1. scan the qrcode to login the wechat user on wechaty
2. click logoff the ipad user on the wechat app
3. the bot will be offline

## 4. Expected behavior

Give a clear and concise description of what you expected to happen.

the `logout` event should be fired.

## 5. Actual behavior

If applicable, add screenshots to help explain your problem. But do not paste log screenshots here.

there's no `logout` event be fired.

```
2019-12-26T16:57:17.084530+00:00 app[web.1]: 16:57:17 VERB Message ready()
2019-12-26T16:57:17.085048+00:00 app[web.1]: 16:57:17 VERB Room ready()
2019-12-26T16:57:37.591625+00:00 app[web.1]: 16:57:37 ERR on-error onError(Error: PADPLUS_ERROR EXIT 你已退出微信)
2019-12-26T16:58:00.378676+00:00 app[web.1]: 16:58:00 ERR Logout WeChat failed! 
```

**Comment by su-chang** [comment]
Thank you for your issue.

The `logout` event will fired 5 seconds later after `error` event fired now.

> ERR Logout WeChat failed!

This bug has been fixed.

Related PR: https://github.com/wechaty/wechaty-puppet-padplus/pull/101

**Comment by huan** [comment]
thanks for the quick response!

I saw your PR force to logout when we run into this situation as a workaround.

Do we need to deal with this ERROR problem, or we should not call that problem an "ERROR"?

**Comment by su-chang** [comment]
There's some different reasons about `logout`, so we let "ERROR" event notify us what reason make WeChat logout. 

Maybe we should create a new event named `notification` so that it could listen on system message, just like `logout reason`. Before the new event created, I think `error` event is better for notify this reason.

And how do you think about create a new event for wechaty named `notification`?

It could used at these ways:
- room (`join`, `topic`)
- contact (`add`, `new`, `delete`)

And then we could distinguish user message and system message.

**Comment by huan** [comment]
I don't think throwing an ERROR for your situation is a good idea.

An ERROR should only be throw out when you have some bad thing that happened and can not recover by yourself.

I'd like to suggest that the puppet should only emit a `logout` event instead of throwing out an ERROR.

**Comment by su-chang** [comment]
I agree, but we can not get the reason of logout when we emit a `logout` event only.

The core problem is that how could let wechaty to show the reason of logout.

**Comment by huan** [comment]
We should try to fix a problem, instead of introducing another problem.

If you need a reason for the `logout` event, we can add a `reason` argument to the `logout` event.

**Comment by su-chang** [comment]
I understand, and I also think it's better to use `logout` event for logout. But **before** we add a `reason` argument for logout, we should emit `error` event for logout's reason as a temp way, otherwise it will make some bugs in our system.

I will create a PR for add `reason` argument for `logout` event later.

**Comment by huan** [comment]
It's ok to keep this Error before we have the `reason` argument for the `logout` event.

Looking forward to your PR soon!

**Comment by su-chang** [comment]
This issue already has been resolved. it will be closed.
