### ISSUE TITLE
There is no messages come after successful authorization.

### ISSUE THREAD

**Issue by Art-in-code** [wechaty/wechaty-puppet-padplus#58]
wechaty-puppet:0.16.1
wechaty: 0.28.3
wechaty-puppet-padplus: 0.1.22
node: v10.15.0
OS Ubuntu 16.04

No errors at logs, just messages don't come. Problem is fluky, in major cases messages come after authorization.

**Comment by jimwting** [comment]
I want to escalate this issue and indicate this is a big problem on the business side because the only way we know about this is if someone recognizes messages are not coming in... which is IMPOSSIBLE to check both WeChat app and Wechaty integration constantly.  

Because there are no errors from Bot Orange's wechaty-puppet-padplus at all, we can only assume token and authentication are good.  We need either a fix to ensure messages are coming through or proper error handling so we can take the necessary actions.  Please provide a target fix date.

**Comment by su-chang** [comment]
Thank for ur issue, let's update the module `wechaty-puppet-padplus` firstly, and then check it again.

Sorry to say that we can not judge the message coming or not, we have put all message in a queue, some special cases,  the message maybe delay.

**Comment by Art-in-code** [comment]
For now we have several stuck accounts. What information should be provided to help you find out what is wrong with those processes?

**Comment by su-chang** [comment]
Could you provide your token to my mailbox, suchang@juzi.bot? And permit me login to check this issue?

**Comment by su-chang** [comment]
Nothing update about this issue, it will be closed.
